# Generated by Django 5.1.3 on 2024-11-22 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_remove_patient_medication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicationLog',
        ),
    ]
